### PR TITLE
Compile with process env

### PR DESCRIPTION
**Pull request by wsw0108**

### CODE REVIEW

**Comment by wsw0108** [comment]
I need to fix `rime-share-data-dir`.

**Comment by DogLooksGood** [comment]
@cnsunyour Could you have a test on Mac to make sure it's still working

**Comment by cnsunyour** [comment]
> @cnsunyour Could you have a test on Mac to make sure it's still working

Yes, it works.

**Comment by DogLooksGood** [comment]
> > @cnsunyour Could you have a test on Mac to make sure it's still working
> 
> Yes, it works.

thanks, I've tested on Linux

**Comment by DogLooksGood** [comment]
looks like there's a little problem with doc, I'll fix it.

**Comment by wsw0108** [comment]
Thanks.

**Pull request merged**
